export const LOADING_BATTLES_LIST = "LOADING_BATTLES_LIST";
export const LOADING_BATTLES_COUNT = "LOADING_BATTLES_COUNT";
export const LOADING_BATTLE_SEARCH = "LOADING_BATTLE_SEARCH";
export const LOADING_SEARCHED_BATTLE = "LOADING_SEARCHED_BATTLE";

export const SHOW_BATTLE_LIST = "SHOW_BATTLE_LIST";
export const SHOW_SEARCHED_BATTLE = "SHOW_SEARCHED_BATTLE";
export const SHOW_BATTLE_COUNT = "SHOW_BATTLE_COUNT";
export const SHOW_SEARCH_LIST = "SHOW_SEARCH_LIST";

export const UPDATE_SEARCH_PARAMS = "UPDATE_SEARCH_PARAMS";
export const UPDATE_SEARCH_BATTLE_ID = "UPDATE_SEARCH_BATTLE_ID";

export const RESET_BATTLE = "RESET_BATTLE";
export const RESET_SEARCHED_BATTLE = "RESET_SEARCHED_BATTLE";